# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/glacier/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    device/htc/glacier/prebuilt/lib/libv8.so:obj/lib/libv8.so \
    device/htc/glacier/prebuilt/lib/libqc-opt.so:obj/lib/libqc-opt.so

PRODUCT_COPY_FILES += \
    device/htc/glacier/prebuilt/bin/akmd:system/bin/akmd \
    device/htc/glacier/prebuilt/bin/awb_camera:system/bin/awb_camera \
    device/htc/glacier/prebuilt/bin/lsc_camera:system/bin/lsc_camera \
    device/htc/glacier/prebuilt/bin/rmt_storage:system/bin/rmt_storage \
    device/htc/glacier/prebuilt/lib/libchromatix_s5k4e1gx_default_video.so:system/lib/libchromatix_s5k4e1gx_default_video.so \
    device/htc/glacier/prebuilt/lib/libchromatix_s5k4e1gx_preview.so:system/lib/libchromatix_s5k4e1gx_preview.so \
    device/htc/glacier/prebuilt/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    device/htc/glacier/prebuilt/lib/libv8.so:system/lib/libv8.so \
    device/htc/glacier/prebuilt/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    device/htc/glacier/prebuilt/lib/libmmosal.so:system/lib/libmmosal.so \
    device/htc/glacier/prebuilt/lib/libmmparser.so:system/lib/libmmparser.so \
    device/htc/glacier/prebuilt/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    device/htc/glacier/prebuilt/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    device/htc/glacier/prebuilt/lib/libqc-opt.so:system/lib/libqc-opt.so \
    device/htc/glacier/prebuilt/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    device/htc/glacier/prebuilt/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    device/htc/glacier/prebuilt/lib/libdiag.so:system/lib/libdiag.so \
    device/htc/glacier/prebuilt/lib/libdnshostprio.so:system/lib/libdnshostprio.so \
    device/htc/glacier/prebuilt/lib/libnetmonitor.so:system/lib/libnetmonitor.so \
    device/htc/glacier/prebuilt/lib/libtcpfinaggr.so:system/lib/libtcpfinaggr.so \
    device/htc/glacier/prebuilt/lib/pp_proc_plugin.so:system/lib/pp_proc_plugin.so \
    device/htc/glacier/prebuilt/lib/qnet-plugin.so:system/lib/qnet-plugin.so \
    device/htc/glacier/prebuilt/lib/tcp-connections.so:system/lib/tcp-connections.so \
    device/htc/glacier/prebuilt/lib/libhtc_ril.so:system/lib/libhtc_ril.so
